# Generated by Django 5.1 on 2025-03-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_guardian_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'No Role'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('guardian', 'Guardian')], default='', max_length=20),
        ),
    ]
